Database model creation
ignaciobockl/pet-business-node pull request #2
Opened 2024-06-03 21:24 UTC by ignaciobockl

- [4a39113] model User

2024-06-07 20:31 UTC, ignaciobockl commented
don't delete branch in merge!!!

2024-06-10 11:24 UTC, ezeamin requested changes

2024-06-10 11:24 UTC, ezeamin commented on package.json
> -    "morgan": "^1.10.0"
por?

2024-06-10 11:24 UTC, ezeamin commented on prisma/schema.prisma
> +  oldPassword String?
para que guardas esto?

2024-06-10 11:24 UTC, ezeamin commented on src/controllers/userController.ts
> +    res.status(201).json(user);
acá estas devolviendo hasta la contraseña

2024-06-10 11:24 UTC, ezeamin commented on src/services/userService.ts
> +        id: uuid,
el id debería generarse automáticamente en la db, no acá

2024-06-10 11:24 UTC, ezeamin commented on src/utils/encryption.ts
> +export const encryptPassword = async (password: string): Promise<string> => {
encriptar no es lo mismo que hashear

2024-06-10 11:24 UTC, ezeamin commented on src/utils/logger.ts
> +  let logMessage = `[${dayjs().format('YYYY-MM-DD HH:mm:ss')} - ${level.toUpperCase()}] ${message}`;
estas reinventando la rueda

2024-06-10 11:24 UTC, ezeamin commented on src/services/userService.ts
> +  if (userData.role === UserRole.ADMIN)
Si hay un solo rol ( + admin), directamente asignalo acá en vez de pedirlo desde el front

2024-06-10 11:24 UTC, ezeamin commented on src/models/Person/person.ts
> +  dni: string;
es necesario el campo dni teniendo cuil?

2024-06-10 11:24 UTC, ezeamin commented on src/controllers/userController.ts
> +    res.status(201).json(user);
Y tampoco usas el formato de `handleResponse`

2024-06-10 23:52 UTC, ignaciobockl commented on package.json
> -    "morgan": "^1.10.0"
se reemplaza por node --watch

2024-06-11 18:22 UTC, ignaciobockl commented on src/controllers/userController.ts
> +    res.status(201).json(user);
no esta terminado, deberia comentarlo la proxima antes de subir, solo tenia listo getAllUsers

2024-06-11 18:29 UTC, ignaciobockl commented on src/services/userService.ts
> +  if (userData.role === UserRole.ADMIN)
no entiendo a que te referis

2024-06-11 18:59 UTC, ignaciobockl commented on src/models/Person/person.ts
> +  dni: string;
los clientes pueden ser fisica(dni) o juridica(cuil), se podria considerar solo dejar el cuil para ambos, armar un enum para tipo de persona para distinguir

2024-06-11 19:00 UTC, ignaciobockl commented on src/utils/logger.ts
> +  let logMessage = `[${dayjs().format('YYYY-MM-DD HH:mm:ss')} - ${level.toUpperCase()}] ${message}`;
podrias explicar un poco mas acerca de que te referis?

2024-06-11 19:05 UTC, ignaciobockl commented on src/utils/encryption.ts
> +export const encryptPassword = async (password: string): Promise<string> => {
si se que no son lo mismo, voy a hacer un estudio para identificar cual es el mas conveniente para implementar.

2024-06-12 10:49 UTC, ezeamin commented on package.json
> -    "morgan": "^1.10.0"
Son dos cosas distintas https://nodejs.org/docs/v20.13.1/api/cli.html#--watch

2024-06-12 10:50 UTC, ezeamin commented on src/controllers/userController.ts
> +    res.status(201).json(user);
Then elimine esto

2024-06-12 10:51 UTC, ezeamin commented on src/utils/logger.ts
> +  let logMessage = `[${dayjs().format('YYYY-MM-DD HH:mm:ss')} - ${level.toUpperCase()}] ${message}`;
No necesitas crear logs manualmente, lo podés hacer con morgan u otras librerías que ya se dedican a esto

2024-06-12 23:59 UTC, ignaciobockl commented on src/utils/logger.ts
> +  let logMessage = `[${dayjs().format('YYYY-MM-DD HH:mm:ss')} - ${level.toUpperCase()}] ${message}`;
perfecto.

2024-06-12 23:59 UTC, ignaciobockl commented on prisma/schema.prisma
> +  oldPassword String?
es el modelo de prisma, lo necesito para generar o regenerar

2024-06-13 01:21 UTC, ignaciobockl commented on package.json
> -    "morgan": "^1.10.0"
tenes razon, estaba confundido, voy a implementarlo y configurarlo correctamente

2024-06-13 20:59 UTC, ignaciobockl commented on src/services/userService.ts
> +        id: uuid,
lo voy a tener en consideracion a la hora de hacer el create.

2024-06-13 21:00 UTC, ignaciobockl commented on src/utils/logger.ts
> +  let logMessage = `[${dayjs().format('YYYY-MM-DD HH:mm:ss')} - ${level.toUpperCase()}] ${message}`;
elimine el logger del proyecto y a futuro voy a implementar libreria pino.
[https://www.npmjs.com/package/pino](url)

2024-06-14 14:08 UTC, ezeamin approved these changes

2024-06-14 14:08 UTC, merged